name: ads-finder-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - audioread==3.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cupy-cuda12x==13.1.0
      - decorator==5.2.1
      - distro==1.9.0
      - dotenv==0.9.9
      - exceptiongroup==1.3.0
      - fastrlock==0.8.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.11.1
      - joblib==1.5.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.43.0
      - msgpack==1.1.2
      - numba==0.60.0
      - numpy==1.26.4
      - openai==2.7.1
      - packaging==25.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - python-dotenv==1.2.1
      - requests==2.32.5
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
prefix: /home/levan/miniconda3/envs/ads-finder-env
